myproject/myproject/myproject/maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'
urlpatterns = [
    path('', views.simple_map),
    path('co-ban/', views.simple_map, name='co-ban'),
    path('tim-kiem/', views.search, name="tim-kiem"),
    path('duong_di/', views.duong_di, name='duong_di'),
]

myproject/myproject/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('gioi-thieu/', views.aboutpage),
    path('maps/', include('maps.urls')),

    path('posts/', include('posts.urls'))
]

myproject/myproject/myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name="list"),
    path('<slug:slug>', views.post_page, name="page")
]

myproject/myproject/myproject/maps/models.py
from django.db import models

# Create your models here.

myproject/myproject/myproject/posts/models.py
from django.db import models

# Create your models here.
class Post (models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

myproject/myproject/myproject/maps/views.py
from django.shortcuts import render

# Create your views here.
def simple_map(request):
    return render(request, 'maps/simple_map.html')

def search(request):
    return render(request, 'maps/search_map.html')

def duong_di(request):
    return render(request, 'maps/duong_di.html')

myproject/myproject/myproject/myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def aboutpage(request):
    return render(request, 'about.html')
def simplemap(request):
    return render(request, 'simple-map.html')

myproject/myproject/myproject/posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse

# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts' : posts})

def post_page(request, slug):
    return HttpResponse(slug)

myproject/myproject/myproject/maps/templates/maps/duong_di.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Hiển thị đường đi{% endblock %}

{% block map %}
<!-- Leaflet -->
<link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
<script src="{% static 'leaflet/leaflet.js' %}"></script>

<!-- Routing Machine -->
<link
  rel="stylesheet"
  href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css"
/>
<script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>

<!-- Geocoder -->
<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
{% endblock %}

{% block content %}
<div class="container">
  <h3 class="text-center">Chọn hai điểm để hiển thị đường đi</h3>
  <div id="map" style="height: 600px;"></div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/map/duong_di.js' %}"></script>
{% endblock %}

myproject/myproject/myproject/maps/templates/maps/search_map.html
{% extends "layout.html" %}
{% load static %}

{% block title %} Tìm kiếm địa vào địa chỉ {% endblock %}

{% block map %}
<link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
<link rel="stylesheet" href="{% static 'css/map/map.css' %}" />
<script src="{% static 'leaflet/leaflet.js' %}"></script>

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/gh/tomickigrzegorz/autocomplete@1.8.6/dist/css/autocomplete.min.css"
/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/tomickigrzegorz/autocomplete@1.8.6/dist/js/autocomplete.min.js"></script>
{% endblock %}

<style>
  .description {
    width: 300px;
    font-size: 16px;
    color: #333;
    padding: 10px 14px;
    background-color: hsla(0, 0%, 100%, 0.8);
    box-shadow: 0 0 15px rgb(0 0 0 / 20%);
    border-radius: 5px;
    line-height: 120%;
    border: 1px solid grey;
  }
</style>

{% block content %}
<section class="special-services">
  <div class="container mb-3">
    <div class="auto-search-wrapper loupe text-center">
      <input
        type="text"
        autocomplete="off"
        id="search"
        placeholder="Nhập vào tên thành phố"
      />
    </div>
  </div>

  <div class="container-fluid">
    <div class="row" style="height: 800px">
      <div id="map"></div>
    </div>
  </div>
</section>
{% endblock %}

{% block script %}
<script src="{% static 'js/map/search-address.js' %}"></script>
{% endblock %}

myproject/myproject/myproject/maps/templates/maps/simple_map.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Bản đồ cơ bản
{% endblock %}

{% block map %}
    <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
    <link rel="stylesheet" href="{% static 'css/map/map.css' %}" />
    <script src="{% static 'leaflet/leaflet.js' %}"></script>
{% endblock %}

{% block content %}
    <section class="special-services">
        <div class="container-fluid">
            <div class="section-title text-center" data-aos="fade-up">
                <h2>Bản đồ cơ bản</h2>
            </div>
            <div class="marker-position"></div>
            <div class="row" style="height: 800px;">
                <div id="map"></div>
            </div>
            <div class="services_mask">
                <img src="{% static 'assets/img/mask/mask9.svg' %}" alt="Icon" class="img-fluid mask_01" />
            </div>
        </div>
    </section>
{% endblock %}

{% block script %}
    <script src="{% static 'js/map/simple.js' %}"></script>
{% endblock %}

myproject/myproject/myproject/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Danh sách bài viết
{% endblock %}


{% block content %}
<section>
    <h1> Danh sách bài viết </h1>
    {% for post in posts %}
        <article class = "post">
            <h2><a href="{% url 'posts:page' slug=post.slug %}"> {{post.title}} </a></h2>
            <p> {{ post.date }} </p>
            <p> {{ post.body }} </p>
        </article>
    {% endfor %}
</section>
{% endblock %}

myproject/myproject/myproject/templates/about.html
{% extends "layout.html" %} 

{% block title %} 
    Giới thiệu 
{% endblock %}

{%block content %}
    <h1>Trang giới thiệu</h1>
    <p>Muốn quay trở lại <a href="/">trang chủ</a></p>
{% endblock %}

myproject/myproject/myproject/templates/footer.html
{% load static %}
<footer>
  <div class="footer-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6 order-lg-0 order-4">
          <div class="footer-area-about mb-50" data-aos="fade-up">
            <h4>About Us</h4>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut
              scelerisque arcu, at porttitor lacus. Integer.
            </p>
            <div class="footer-area-links">
              <a href="javascript:void(0)"><i class="fab fa-facebook-f"></i></a>
              <a href="javascript:void(0)"><i class="fab fa-twitter"></i></a>
              <a href="javascript:void(0)"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
        <div class="col-lg-2 mr-lg-65 col-md-4 col-6 order-lg-0 order-md-1">
          <div
            class="footer-area-lists mb-30"
            data-aos="fade-up"
            data-aos-delay="300"
          >
            <h4>Company</h4>
            <ul>
              <li>
                <a href="/gioi-thieu">About us</a>
              </li>
              <li>
                <a href="/">Contact us</a>
              </li>
              <li>
                <a href="/">Careers</a>
              </li>
              <li>
                <a href="/">Press</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-2 mr-lg-65 col-md-4 col-6 order-lg-0 order-2">
          <div
            class="footer-area-lists mb-30"
            data-aos="fade-up"
            data-aos-delay="400"
          >
            <h4>Products</h4>
            <ul>
              <li>
                <a href="/">Features</a>
              </li>
              <li>
                <a href="/">Pricing</a>
              </li>
              <li>
                <a href="/">News</a>
              </li>
              <li>
                <a href="/">Help desk</a>
              </li>
              <li>
                <a href="/">Support</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-2 col-md-4 col-6 order-lg-0 order-md-3">
          <div
            class="footer-area-lists"
            data-aos="fade-up"
            data-aos-delay="500"
          >
            <h4>Legal</h4>
            <ul>
              <li>
                <a href="/">Privacy Policy</a>
              </li>
              <li>
                <a href="/">Terms & Conditions</a>
              </li>
              <li>
                <a href="/">Return Policy</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-area-shape">
      <img
        data-aos="fade-down"
        data-aos-easing="linear"
        data-aos-delay="600"
        src="{% static 'assets/img/mask/penta-02.svg' %}"
        alt="shape"
        class="img-fluid ft-shape-01"
      />
      <img
        data-aos="fade-down"
        data-aos-easing="linear"
        data-aos-delay="700"
        src="{% static 'assets/img/mask/downShape.svg' %}"
        alt="shape"
        class="img-fluid ft-shape-02"
      />
      <img
        data-aos="fade-left"
        data-aos-easing="linear"
        data-aos-delay="500"
        src="{% static 'assets/img/mask/circle-01.svg' %}"
        alt="shape"
        class="img-fluid ft-shape-03"
      />
    </div>
  </div>
  <!-- copyright area -->
  <div class="copyright">
    <div class="container">
      <div class="row align-items-center copyright-area">
        <div class="col-lg-5 col-md-4 col-sm-12">
          <div class="copyright-area-text">
            <p>Copyright 2020. All Rights Reserved by us!</p>
          </div>
        </div>

        <div class="col-lg-2 col-md-4 col-sm-12">
          <div class="copyright-area-logo">
            <a href="/">
              <img
                src="{% static 'assets/img/logo/logo.png' %}"
                alt="logo"
                class="img-fluid"
              />
            </a>
          </div>
        </div>

        <div class="col-lg-5 col-md-4 col-sm-12">
          <div class="copyright-area-top text-lg-right">
            <a href="#header" id="to-top"
              >Back to Top <i class="fas fa-angle-up"></i
            ></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

myproject/myproject/myproject/templates/header.html
{% load static %}
<header id="header" class="header-area">
  <div class="container custom-container">
    <nav class="menu-area d-flex align-items-center">
      <div class="logo">
        <a href="index.html">
          <img src="{% static 'assets/img/logo/logo.png' %}" alt="logo" />
        </a>
      </div>
      <ul class="main-menu d-flex align-items-center">
        <li class="active"><a href="/">Trang chủ</a></li>
        <li>
          <a href="{javascript:void(0)}">Bản đồ</a>
          <ul class="sub-menu">
            <li><a href="{% url 'maps:co-ban' %}">Cơ bản</a></li>
            <li><a href="{% url 'maps:tim-kiem' %}">Tìm kiếm</a></li>
            <li><a href="{% url 'maps:duong_di' %}">Duong di</a></li>
            <li><a href="/ECU-ban/">ECU bản</a></li>
          </ul>
        </li>
        <li><a href="/gioi-thieu/">Giới thiệu</a></li>
      </ul>
      <div class="right-content ml-auto">
        <div class="search-bar">
          <img
            src="{% static 'assets/img/logo/search.svg' %}"
            alt="search logo"
          />
        </div>
        <div class="hamburger-menu">
          <span></span><span></span><span></span>
        </div>
      </div>
    </nav>
  

<aside>
  <div class="sidebar-menu">
    <div class="close-sidebar"><span></span><span></span></div>
    <div class="logo">
      <a href="index.html">
        <img src="{% static 'assets/img/logo/logo.png' %}" alt="logo" />
      </a>
    </div>
    <form class="asidesearch-bar">
      <input type="text" name="search" />
      <img src="{% static 'assets/img/logo/search.svg' %}" alt="search logo" />
    </form>
  </div>
  <div class="overlay"></div>
</aside>

<div class="search-box">
  <div class="search-form">
    <form action="#">
      <input type="text" placeholder="Enter Your Keyword" />
    <button type="submit">
      <img src="{% static 'assets/img/logo/search.svg' %}" alt="search logo" />
    </button>
</form>
  </div>
  <a class="search-close" href="javascript:void(0)">
    <i class="fas fa-times"></i>
  </a>
</div>
</div>
</header>

myproject/myproject/myproject/templates/home.html
{% extends "layout.html" %} 

{% block title %} 
    Trang chủ 
{% endblock %}

{%block content %}
<h1>Trang chủ</h1>
<p>Để xem thêm chi tiết <a href="/gioi-thieu">tại đây</a></p>
{% endblock %}

myproject/myproject/myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ứng dụng bài viết{% endblock %}</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    {% block map %}
    {% endblock %}
</head>
<body>

    {% include 'header.html' %}

    <main style="position: relative; min-height: 100%; height: 100%;">
    
        {% block content %}
        
        {% endblock %}
        
        {% block script %}
        
        {% endblock %}
    
    </main>
    

    {% include 'footer.html' %}

    <!-- JavaScript -->
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/circle-progress.min.js' %}"></script>
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets/js/slider.js' %}"></script>
    <script src="{% static 'assets/js/aos.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

    <script> 
        /* magnificPopup video view */
        document.addEventListener("DOMContentLoaded", function() {
            if (typeof jQuery !== "undefined") {
                $('.popup-video').magnificPopup({
                    type: 'iframe',
                });
            } else {
                console.error("jQuery is not loaded. Please check your script order.");
            }
        });
    </script>

</body>
</html>